//
//  UsersViewControllerTests.swift
//  CleanSwiftSample
//
//  Created by Parveen Bhatia on 3/27/18.
//  Copyright (c) 2018 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanSwiftSample
import XCTest

class UsersViewControllerTests: XCTestCase
{
    // MARK: Subject under test
    var sut: UsersViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        window = UIWindow()
        setupUsersViewController()
    }
    
    override func tearDown()
    {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupUsersViewController()
    {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: "UsersViewControllerId") as! UsersViewController
    }
    
    func loadView()
    {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    class UsersBusinessLogicSpy: UsersBusinessLogic
    {
        var loadUsersCalled = false
        
        func loadUsers(request: Users.Request) {
            loadUsersCalled = true
        }
    }
    
    // MARK: Tests
    
    func testShouldLoadUsersViewIsLoaded()
    {
        // Given
        let spy = UsersBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        
        // Then
        XCTAssertTrue(spy.loadUsersCalled, "viewDidLoad() should ask the interactor to load users")
    }
    
}
