//
//  UsersWorkerTests.swift
//  CleanSwiftSample
//
//  Created by Parveen Bhatia on 3/27/18.
//  Copyright (c) 2018 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanSwiftSample
import XCTest

class UsersWorkerTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: UsersWorker!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupUsersWorker()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupUsersWorker()
    {
        sut = UsersWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testGetUsers()
    {
        // Given
        
        // When
        
        // Then
    }
}
